pipeline {
    agent any

    parameters {
        choice (name: "REPOSITORY", choices: ['https://github.com/Mnarique217/devops-challenge.git'],description: "repository to build")
    }

    stages {
        stage('CHECKOUT') {
            steps {
                dir('build'){
                    git branch: 'feature/jenkis', url: params.REPOSITORY
                }
            }
        }

        stage('STATIC-CODE-ANALISIS') {
            steps {
                dir('build'){
                sh '''
                    tfsec ./terraform
                '''
                }
            }
        }

        stage('BUILD') {
            steps {
                dir('build'){
                sh '''
                    cd application
                    buildah bud --format=docker -f ./Dockerfile -t 192.168.49.1:5000/app:env.BUILD_NUMBER
                    buildah --tls-verify=false push 192.168.49.1:5000/app:9.9.9
                '''
                }
            }
        }

        stage('SECURITY-SCANNING') {
            steps {
                dir('build'){
                sh '''
                    trivy
                '''
                }
            }
        }

        stage('DEPLOYMENT') {
            steps {
                dir('build'){
                    withCredentials([file(credentialsId: 'kube-config', variable: 'KUBE_CONFIG')]) {
                    sh '''
                    KUBECONFIG=$KUBE_CONFIG
                    helm install 
                    '''            
                    }                    
                }
            }
        }

        stage('ROLLBACK') {
            steps {
                dir('build'){
                sh '''
                    kubectl 
                    helm
                '''
                }
            }
        }
    }
}